baseurl = "http://alfiepates.me/"
languageCode = "en-uk"
title = "Alfie Pates"
theme = "hyde-x"


[author]
    name = "Alfie Pates"

[params]
   truncate = false
   theme = "theme-base-0c layout-reverse"
   tagline = "Audio and development ramblings"
   github = "http://github.com/alfiepates/"

[taxonomies]
   tag = "tags"
